version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "127.0.0.1:5000:5000"   # Expose Flask app only to localhost
    env_file:
      - .env
    volumes:
      - ./app:/app             # Mount app folder for development
    depends_on:
      - db
    restart: on-failure        # Restart only on crashes

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "127.0.0.1:3306:3306"  # Expose MySQL only to localhost
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: on-failure        # Restart only on crashes

volumes:
  mysql_data:
